name: NTM_MainPlugin
version: '${project.version}'
main: by.quaks.ntm.ntm_mainplugin.NTM_MainPlugin
api-version: 1.18
commands:
  msg:
    aliases:
      - m
      - tell
      - w
    description: Отпраыить личное сообщение
    usage: /msg Никнейм
  burp:
    description: Смачно burp'нуть
    usage: /burp
  ignore:
    description: Игнорировать сообщения от человека в ЛС
    usage: /ignore Никнейм
  permmute:
    description: Выдан мут
    usage: /mute Никнейм
    aliases:
      - pmute
depend:
  - DiscordSRV
