name: NTM_MainPlugin
version: '${project.version}'
main: by.quaks.ntm.ntm_mainplugin.NTM_MainPlugin
api-version: 1.18
commands:
  tell:
    aliases:
      - m
    description: Отпраыить личное сообщкние
    usage: /tell Никнейм
