name: NTM
version: '${project.version}'
main: by.quaks.ntm.NTM
api-version: 1.18
commands:
  msg:
    aliases:
      - m
      - tell
      - w
    description: Отправить личное сообщение
    usage: /msg Никнейм
  burp:
    description: Смачно burp'нуть
    usage: /burp
  ignore:
    description: Игнорировать сообщения от человека в ЛС
    usage: /ignore Никнейм
  mute:
    description: Выдан мут
    usage: /mute Никнейм Вре мя
  reply:
    description: Быстрый ответ
    usage: /reply
    aliases:
      - r
  autograph:
    description: Подписать предмет
    usage: /autograph
    aliases:
      - aph
  report:
    description: Написать репорт
    usage: /report
  protect:
    description: Защитить карту от копирования
    usage: /protect
depend:
  - DiscordSRV
